
name: Zip repo to magento extension
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Magento extension zip
      uses: thedoctor0/zip-release@master
      with:
        filename: 'knawat-module-dropshipping.zip'
        exclusions: '*.git* .gitignore */vendor*'
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/knawat-module-dropshipping.zip
        asset_name: knawat-module-dropshipping.zip
        asset_content_type: application/zip
